<?php
/**
 * @author Martin Gamboa Vazquez
 * @version 1.0.0
 * @created 2022-05-14
 * @final En proceso
 *
 */
namespace gamboamartin\acl\controllers;

use gamboamartin\errores\errores;
use gamboamartin\system\system;
use stdClass;



class _ctl_base extends system{

    /**
     * Integra los campos view de una vista para alta y modifica
     * @return array
     * @version 0.73.1
     */
    protected function campos_view(): array
    {
        return array();
    }

    /**
     * Integra los elementos base de una view
     * @return array|$this
     * @version 0.73.1
     */
    private function base(): array|static
    {

        $campos_view = $this->campos_view();
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al maquetar campos_view',data:  $campos_view);
        }

        $this->modelo->campos_view = $campos_view;



        $this->inputs = new stdClass();
        $this->inputs->select = new stdClass();


        return $this;
    }

    /**
     * Inicializa loe elementos para un alta
     * @return array|stdClass|string
     * @version 0.73.1
     */
    protected function init_alta(): array|stdClass|string
    {

        $r_template = parent::alta(header:false); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al obtener template',data:  $r_template);
        }

        $base = $this->base();
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al genera base',data:  $base);
        }

        return $r_template;
    }

    /**
     * Inicializa upd base view
     * @return array|stdClass|string
     * @version 0.74.1
     */
    protected function init_modifica(): array|stdClass|string
    {
        if($this->registro_id<=0){
            return $this->errores->error(mensaje: 'Error registro_id debe ser mayor a 0', data: $this->registro_id);
        }

        $r_template = parent::modifica(header: false); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al obtener template',data:  $r_template);
        }

        $base = $this->base();
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al genera base',data:  $base);
        }
        return $r_template;
    }

}
