<?php
/**
 * @author Martin Gamboa Vazquez
 * @version 1.0.0
 * @created 2022-05-14
 * @final En proceso
 *
 */
namespace gamboamartin\acl\controllers;

use gamboamartin\administrador\models\adm_accion_grupo;
use gamboamartin\administrador\models\adm_grupo;
use gamboamartin\administrador\models\adm_usuario;
use gamboamartin\errores\errores;
use gamboamartin\system\html_controler;
use gamboamartin\system\system;
use gamboamartin\template_1\html;
use html\adm_accion_html;
use html\adm_grupo_html;
use html\adm_menu_html;
use html\adm_seccion_html;
use html\adm_usuario_html;
use links\secciones\link_adm_grupo;
use PDO;
use stdClass;


class controlador_adm_grupo extends _ctl_parent {

    public array $secciones = array();
    public stdClass|array $adm_grupo = array();
    public array $adm_acciones_grupo = array();
    public string $link_adm_usuario_alta_bd = '';
    public string $link_adm_accion_grupo_alta_bd = '';
    public array $adm_usuarios = array();

    public function __construct(PDO $link, html $html = new html(), stdClass $paths_conf = new stdClass()){
        $modelo = new adm_grupo(link: $link);

        $html_ = new adm_grupo_html(html: $html);
        $obj_link = new link_adm_grupo(link: $link,registro_id:  $this->registro_id);

        $datatables = new stdClass();
        $datatables->columns = array();
        $datatables->columns['adm_grupo_id']['titulo'] = 'Id';
        $datatables->columns['adm_grupo_codigo']['titulo'] = 'Cod';
        $datatables->columns['adm_grupo_descripcion']['titulo'] = 'Grupo';
        $datatables->columns['adm_grupo_n_permisos']['titulo'] = 'N Permisos';
        $datatables->columns['adm_grupo_n_usuarios']['titulo'] = 'N Usuarios';

        $datatables->filtro = array();
        $datatables->filtro[] = 'adm_grupo.id';
        $datatables->filtro[] = 'adm_grupo.codigo';
        $datatables->filtro[] = 'adm_grupo.descripcion';


        parent::__construct(html: $html_, link: $link, modelo: $modelo, obj_link: $obj_link, datatables: $datatables,
            paths_conf: $paths_conf);

        $this->titulo_lista = 'Grupos';

        if(isset($this->registro_id) && $this->registro_id > 0){
            $adm_grupo = (new adm_grupo($this->link))->registro(registro_id: $this->registro_id);
            if(errores::$error){
                $error = $this->errores->error(mensaje: 'Error al obtener adm_grupo',data:  $adm_grupo);
                print_r($error);
                exit;
            }
            $this->adm_grupo = $adm_grupo;
        }

        $link_adm_usuario_alta_bd = $this->obj_link->link_alta_bd(link: $link, seccion: 'adm_usuario');
        if(errores::$error){
            $error = $this->errores->error(mensaje: 'Error al obtener link',data:  $link_adm_usuario_alta_bd);
            print_r($error);
            exit;
        }
        $this->link_adm_usuario_alta_bd = $link_adm_usuario_alta_bd;

        $link_adm_accion_grupo_alta_bd = $this->obj_link->link_alta_bd(link: $link, seccion: 'adm_accion_grupo');
        if(errores::$error){
            $error = $this->errores->error(mensaje: 'Error al obtener link',data:  $link_adm_accion_grupo_alta_bd);
            print_r($error);
            exit;
        }
        $this->link_adm_accion_grupo_alta_bd = $link_adm_accion_grupo_alta_bd;

    }

    public function alta(bool $header, bool $ws = false): array|string
    {
        $r_alta = parent::alta(header:false); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->retorno_error(
                mensaje: 'Error al obtener template',data:  $r_alta, header: $header,ws:  $ws);
        }

        $this->modelo->campos_view = array();
        $this->modelo->campos_view['codigo']['type'] = 'inputs';

        $this->modelo->campos_view['descripcion']['type'] = 'inputs';


        $this->inputs = new stdClass();
        $this->inputs->select = new stdClass();


        $keys_selects['codigo'] = new stdClass();
        $keys_selects['codigo']->cols = 12;
        $keys_selects['codigo']->place_holder = 'Cod';


        $keys_selects['descripcion'] = new stdClass();
        $keys_selects['descripcion']->cols = 12;
        $keys_selects['descripcion']->place_holder = 'Grupo';


        $inputs = $this->genera_inputs(keys_selects: $keys_selects);
        if(errores::$error){
            return $this->retorno_error(
                mensaje: 'Error al obtener inputs',data:  $inputs, header: $header,ws:  $ws);
        }


        return $r_alta;
    }

    public function asigna_permiso(bool $header = true, bool $ws = false): array|stdClass{

        if($this->registro_id<=0){
            return $this->errores->error(mensaje: 'Error this->registro_id debe ser mayor a 0',
                data:  $this->registro_id);
        }

        $adm_grupo = $this->modelo->registro(registro_id: $this->registro_id, retorno_obj: true);
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al obtener adm_grupo',data:  $adm_grupo);
        }

        $select_adm_grupo_id = (new adm_grupo_html(html: $this->html_base))->select_adm_grupo_id(
            cols:12,con_registros: true,id_selected: $this->registro_id,link:  $this->link, disabled: true);

        if(errores::$error){
            return $this->retorno_error(
                mensaje: 'Error al obtener select_adm_accion_id',data:  $select_adm_grupo_id, header: $header,ws:  $ws);
        }

        $select_adm_menu_id = (new adm_menu_html(html: $this->html_base))->select_adm_menu_id(
            cols:6,con_registros: true,id_selected: -1,link:  $this->link);

        if(errores::$error){
            return $this->retorno_error(
                mensaje: 'Error al obtener select_adm_accion_id',data:  $select_adm_grupo_id, header: $header,ws:  $ws);
        }

        $select_adm_seccion_id = (new adm_seccion_html(html: $this->html_base))->select_adm_seccion_id(
            cols:6,con_registros: false,id_selected: -1,link:  $this->link);

        if(errores::$error){
            return $this->retorno_error(
                mensaje: 'Error al obtener select_adm_accion_id',data:  $select_adm_grupo_id, header: $header,ws:  $ws);
        }

        $select_adm_accion_id = (new adm_accion_html(html: $this->html_base))->select_adm_accion_id(
            cols:12,con_registros: false,id_selected: -1,link:  $this->link);

        if(errores::$error){
            return $this->retorno_error(
                mensaje: 'Error al obtener select_adm_accion_id',data:  $select_adm_grupo_id, header: $header,ws:  $ws);
        }

        $hidden_adm_grupo_id = (new adm_grupo_html(html: $this->html_base))->hidden(name: 'adm_grupo_id', value: $this->registro_id);
        if(errores::$error){
            return $this->retorno_error(
                mensaje: 'Error al obtener hidden_adm_seccion_id',data:  $hidden_adm_grupo_id, header: $header,ws:  $ws);
        }


        $retornos = (new html_controler(html: $this->html_base))->retornos(registro_id: $this->registro_id,tabla:  $this->tabla);
        if(errores::$error){
            return $this->retorno_error(
                mensaje: 'Error al obtener retornos',data:  $retornos, header: $header,ws:  $ws);
        }

        $this->inputs = new stdClass();
        $this->inputs->select = new stdClass();

        $this->inputs->select->adm_grupo_id = $select_adm_grupo_id;
        $this->inputs->select->adm_menu_id = $select_adm_menu_id;
        $this->inputs->select->adm_seccion_id = $select_adm_seccion_id;
        $this->inputs->select->adm_accion_id = $select_adm_accion_id;
        $this->inputs->hidden_adm_grupo_id = $hidden_adm_grupo_id;

        $this->inputs->hidden_seccion_retorno = $retornos->hidden_seccion_retorno;
        $this->inputs->hidden_id_retorno = $retornos->hidden_id_retorno;


        $adm_acciones_grupo = (new adm_accion_grupo($this->link))->acciones_por_grupo(adm_grupo_id: $this->registro_id);
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al obtener adm_acciones_grupo',data:  $adm_acciones_grupo, header: $header,ws:  $ws);
        }

        $adm_acciones_grupo = $this->rows_con_permisos(key_id:  'adm_accion_grupo_id',rows:  $adm_acciones_grupo,seccion: 'adm_accion_grupo');
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al integrar links',data:  $adm_acciones_grupo, header: $header,ws:  $ws);
        }

        $this->adm_acciones_grupo = $adm_acciones_grupo;


        return $adm_grupo;
    }

    public function usuarios(bool $header = true, bool $ws = false){
        if($this->registro_id<=0){
            return $this->errores->error(mensaje: 'Error this->registro_id debe ser mayor a 0',
                data:  $this->registro_id);
        }
        $adm_grupo = $this->modelo->registro(registro_id: $this->registro_id, retorno_obj: true);
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al obtener adm_grupo',data:  $adm_grupo);
        }

        $select_adm_grupo_id = (new adm_grupo_html(html: $this->html_base))->select_adm_grupo_id(
            cols:12,con_registros: true,id_selected:  $adm_grupo->adm_grupo_id,link:  $this->link, disabled: true);

        if(errores::$error){
            return $this->retorno_error(
                mensaje: 'Error al obtener select_adm_grupo_id',data:  $select_adm_grupo_id, header: $header,ws:  $ws);
        }

        $adm_usuario_user = (new adm_usuario_html(html: $this->html_base))->input_user(
            cols:6,row_upd:  new stdClass(),value_vacio:  false);
        if(errores::$error){
            return $this->retorno_error(
                mensaje: 'Error al obtener adm_usuario_user',data:  $adm_usuario_user, header: $header,ws:  $ws);
        }

        $adm_usuario_password = (new adm_usuario_html(html: $this->html_base))->input_password(
            cols:6,row_upd:  new stdClass(),value_vacio:  false);
        if(errores::$error){
            return $this->retorno_error(
                mensaje: 'Error al obtener adm_usuario_password',data:  $adm_usuario_password, header: $header,ws:  $ws);
        }

        $adm_usuario_email = (new adm_usuario_html(html: $this->html_base))->input_email(
            cols:6,row_upd:  new stdClass(),value_vacio:  false);
        if(errores::$error){
            return $this->retorno_error(
                mensaje: 'Error al obtener adm_usuario_email',data:  $adm_usuario_email, header: $header,ws:  $ws);
        }

        $adm_usuario_telefono = (new adm_usuario_html(html: $this->html_base))->input_telefono(
            cols:6,row_upd:  new stdClass(),value_vacio:  false);
        if(errores::$error){
            return $this->retorno_error(
                mensaje: 'Error al obtener adm_usuario_telefono',data:  $adm_usuario_telefono, header: $header,ws:  $ws);
        }

        $hidden_adm_grupo_id = (new adm_grupo_html(html: $this->html_base))->hidden(name: 'adm_grupo_id', value: $this->registro_id);
        if(errores::$error){
            return $this->retorno_error(
                mensaje: 'Error al obtener hidden_adm_seccion_id',data:  $hidden_adm_grupo_id, header: $header,ws:  $ws);
        }


        $retornos = (new html_controler(html: $this->html_base))->retornos(registro_id: $this->registro_id,tabla:  $this->tabla);
        if(errores::$error){
            return $this->retorno_error(
                mensaje: 'Error al obtener retornos',data:  $retornos, header: $header,ws:  $ws);
        }

        $adm_usuarios = (new adm_usuario($this->link))->usuarios_por_grupo(adm_grupo_id: $this->registro_id);
        if(errores::$error){
            return $this->retorno_error(
                mensaje: 'Error al obtener adm_usuarios',data:  $adm_usuarios, header: $header,ws:  $ws);
        }

        $adm_usuarios = $this->rows_con_permisos(key_id:  'adm_usuario_id',rows:  $adm_usuarios,seccion: 'adm_usuario');
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al integrar link',data:  $adm_usuarios, header: $header,ws:  $ws);
        }

        $this->adm_usuarios = $adm_usuarios;

        $this->inputs = new stdClass();
        $this->inputs->select = new stdClass();
        $this->inputs->select->adm_grupo_id = $select_adm_grupo_id;
        $this->inputs->adm_usuario_user = $adm_usuario_user;
        $this->inputs->adm_usuario_password = $adm_usuario_password;
        $this->inputs->adm_usuario_email = $adm_usuario_email;
        $this->inputs->adm_usuario_telefono = $adm_usuario_telefono;
        $this->inputs->hidden_adm_grupo_id = $hidden_adm_grupo_id;
        $this->inputs->hidden_seccion_retorno = $retornos->hidden_seccion_retorno;
        $this->inputs->hidden_id_retorno = $retornos->hidden_id_retorno;


    }


}
